//
//  CodeObfuscation.h
//  PHPocket
//
//  Created by 白翔龙 on 2023/2/6.
//

#ifndef CodeObfuscation_h
#define CodeObfuscation_h

#define getSelectData OmWJoTZfCqoPshvr
#define JKPickerViewAppearance egnjoOFDrFiQVRgr
#define setUserInfoValue gKKpJrMeOMzHLE_g
#define getUserInfoValueForKey reXYcdSKKEUSMalJxx
#define showTip reXYcdSKKEUSMalJcdsa
#define showAlertWithText mHEQViTuoOvRtMuBsstehga
#define setupNavBarSubView TuosjdjhaOvE
#define showSimpleLoading TuUHSHDUOhaOvEsb
#define showImageAnimationLoading TuUHSDHARQ6HDUOhaOvE
#define backToAppointedController ATGDjsj54uUHSDH
#define showPhHud ATshowPhHudss
#define dismissphHud ATdismissphHuddd
#define hideLoading ATdismssshideLoadhHuddd
#define hudHidenWhenComplete Agshdghsquwuh
#define cellWithTableView NMAjrthajass
#define showUserProtoclAndPrivacy gawWUEUNgNnd53ssh
#define firstStartAppNextOperation vdajhWOAHUTolsihd
#define setupSubView NimdTYUSBDHJS
#define requsestHomeData NimdTYHGAHSGHAUSBDHJS
#define setActivityView NiSTRSGS6HWH_O
#define updateHomeStatus ssbshgdSTWRSeeS6HWH_O
#define updateVersion sssryghTYAYG6HWH_H
#define requestAlreadyGetCounponList bvcaUHSJHEIUSgdgd
#define requestSureCounponList bGDHSAatwybsQDHgdh
#define reloanApply gdhasgdwiuTYGQYbs
#define payPasswordView GSsgsYugwSGSG
#define pushLoanLevelVc GSsgsYtYWugGeqhsh
#define pushSomeVc FDwgegGSHGHS
#define pushSelectLoanMethed FDwpushSelectLoanMethedGHS
#define pushdrawalMoneyVc FDwpunMethedGHSpusMoneyVc
#define requestRiskData SGHSrequestRiskDataSHH
#define requestWarmMessage requestWarmMessageghag
#define getUserLoction sssdegetUserLoctiondd
#define getRapayData GAHgetSelectDataghh
#define goQinglun GgoQinglunhh
#define pushFeedbackVc svHSHpushFeedbackVcS
#define getJkRiskData svHSHsizeWithTextVcS
#define getRiskDataWithCatchID GSHGHAgetRiFSFtaWithCatchIDGHSG
#define withApplyId GSHGHwithApUplyIdDGHSG
#define withDetailId wddlydwithDetSG
//PHTabBarController
#define setUpAllChildViewController wddlydwisetUpAllCthDetSG
#define setUpOneChildViewController wdsetUpOneChildViewControllerhDetSG
//PHNavigationController
#define setUpNavBarButton DDWsetUpNavBarButtonSG
#define popToRoot hdjsjpopToRootntrollerSG
#define popToPre hdpopToPrerSG
//PHUserProtocalAndPrivacyViewController
#define PHUserProtocalAndPrivacyViewController gdaUhshWUQBBAViewController
#define createSubView gdcreateSubViewtrollersDDSTVs
//PHTipsViewController
#define PHTipsViewController gdaUhshWUQBBddbAViewController
#define pushCerCoreVc gteUUshWUQBBddbpushVc
//PHMyViewController
#define pushLoginVc TEGasetupSubViewpushLoginVcSVS
#define pushSetupVc gteSRGSetupVcbpushVc
#define pushAboutVc gtpushAboutVcDGHASG
#define pushAssistanceVc gtpGDUGpushAssistanceVccDGHASG
#define pushLoadRecrdVc gtGDGDGPPSVpushFeedbackVcVccDGHASG
#define showAlertView TBWGSGhgfbfcDGHASG
//JKPhoneLoginViewController
#define JKPhoneLoginViewController TBJKsAccountsdeToolASGVC
#define setupSubviews TBJsetupSubviewstsdeToolASGVC
#define httpLogin TBJsehdttpLogin
#define withPassWord TBwithPassWordLogin
#define isCanUsePhone TwgdFswisCanUsePhoneWordLogiSV
//JKJobInfomationViewController
#define JKJobInfomationViewController TwgdFswJKJobInfomationVcHDV
#define dealWithData TwgdFdealWithDatadnVcHDV
#define setupFootView TwgdsetdeeupFootViewVcHDV
#define clickSubmitBtn TclickSubmiagvwcHDV
#define sutupAlertView sDDsutupAlertViewvwcHDVS
#define withData sDwithDataVHDVS
#define resetDataWithTitle sDwresetDSSataWithTDDDitleVHDVS
#define selectAdrress sDwselSSectSSAdSSrresseVHDVS
#define areaPickerView sDwseareaPickerViewSSREsseVHDVS
#define didTableViewRowWithModel sDwfghViewRowWithModelVHDVS
#define updateDataWithTitle sDwfghVswewqfhModelshjvabhvVS
#define pushAddressVc sDwfghVpushAddredrvvVS
#define BTAreaPickViewController sDwdjaBTAreaPickViewControllersw
#define JKIDAuthentificationViewController sDwdjaJKIDAuthentificgahwvlersw
#define getCacheData sDgetCacheDatWDersw
#define getImgCach sDggetImgCacHAHersw
#define getAliyunUpLoadImag sDsHJVSAHagAHersw
#define clickIDCardCamera sDseclickIDCardCacliJSBHJSAHersw
#define customImagePickerController sDseclcustomImagePickerContrHersw
#define requstUploadImgeUrl EFrequstUploadImgHer
#define upLoadUserInfo wFrequpLoadUserInfogHer
#define requestOrc_Info wFrrequestOrc_InfoInfogHer
#define backUpLoadUserInfo wFrreqbackUpLoadUserInfoogHer
#define birthdayPickerView wFbirthdayPickerViewer
#define showFaceAlert FDVxshowFaceAlertDrViewer
#define showCardAlert hgssshowCardAlertTEG
#define canUserCamear GFgcanUserCamearertTEG
#define camearAuthAlert YTcamearAutREGrtTEG
//#define getAliyunToken VCameagetAliyunTokenGrtTEG
#define pushCerterVc HGJAHGDA63gshfhds
#define getCamearAuthSeletsAlert HGJgetCafsgtgdgdlerthfhds
#define faceRecognition HGJfaceRecognitrthfhds
#define requestFaceImage dwhggRTuestFaceImagetrthfhds
#define requestIDCardType rWDbdbEBCetrtvscbdb
//JKUploadAttachViewController
#define JKUploadAttachViewController rfdJKUploadAttachViewContrTRBdb
#define setupDtat rfsetupDtCrTRBdb
#define getCacheImageWithKey dcWfgetCacheImageWithKeyFS
#define selectPhoto deESselectPhotoageWithKeyFS
//JKEmergencyContactViewController
#define JKEmergencyContactViewController dritcanUserCamearyFSVXCS
#define setupContactWithName drisvcREupContactWithNameyEdS
#define withPhone driwithPhonethNameyEdS
#define saveUserInfoHttp drfsEUEHUAHsaveUserInfoHttP
#define selectPersonContactPickerVc dRsgsTTsselectPersGSHc
#define pushIDVc dRspushIDVcGSHcdx
//JKBasicInformationViewController
#define loadHzArray dRsploadHzArrsSHcdx
#define setInitStringWithKey CVspdealWithDatarQSs
#define creatEmeil CVscreatEmetarQSs
#define setupEmaiData CsetupDHGDHgsgEmaiDatas
#define isCanUsePhoneWithNum CssaveUsvhhInfoHttpgfsas
#define isEmailWithSting CssgttpgfsasFDGG
//JKFeedbackViewController
#define JKFeedbackViewController CssJKFeedbackViewControllersWSG
#define createSegMentController CscreateSegMentContrsDS
#define indexDidChangeForSegmentedControl SCEReSegMentindexDidChegmentedControl
#define setupTextViews HJVJADAvssgh5SHSsbsj
#define convertToInt HteconvertToInRWGj
#define clickUpLoadPhoto sdclickUpLoadPhotoCXj
#define requestAskMind sdclrequestAskMinds
#define openPhotoLibrary sdopenPhotoLibrarDs
#define UIImageToBase64Str sdUIImageToBase64StrarDs
//JKCouponAlertViewOneCell
#define JKCouponAlertViewOneCell gshJKCouponAlertViewOneCellrarDs
#define resetCoupon GDFresetCouponewOneCellGEgdg
#define JKBaseCell GDFJgdBaseCellOhdhneCellGEsgdssg
#define setContentStr GDFJgdBsetContentStrds
#define erp_setupSubviews GDFJeterp_setupSubviewsgdBs
#define JKCouponAlertViewCell sggFJeterp_gsgshwsgCells
#define JKCouponFootView gdfsfgaeJKCouponFootViewhsgh6t
//JKRepaymentCenterViewController
#define JKRepaymentCenterViewController gdJKRepaymentgsntrollergshh6t
#define pushCouponAlert PAHpushCouponAlDDertsgh6t
#define requestRepayData PAHpGSJHrequestRepayDatalDDertsgh6t
#define requestRepayMoney PAHpGSJHrequGSHSrequestRepayMoneyDDertsgh6t
#define pushRepaymentVc HSHSHpushRepaymegh6t
#define pushNewRepaymentVc HSHSpushNewRvdvepaymentVcffdsgh6t
#define showFullPaymentAlert HDCSshowFullPaymfvsvsntVcffdsgh6t
#define showNoFullPayAlertView FSGGSshowNoFuYWTlertViewHS
#define showLoanAgreementAlert FSGshowLoanAgreemenydr5HS
#define pushWebView FSGspushWesssbViewDSdr5HS
#define JKLoanAgreementAlert BCSSSErequestWarmMessE5HS
#define loanWarmAlertWithContent cxSSSEloanWarmAlertWithCer5HS
#define JKNoFullPayAlertView cCounponListtWithCer5HS
#define defaultUseCounpon cGSevsvltUseCounpontUseCounjS
#define JKRepaymentCenterViewCell cGyyeJKRepaymentCenterViewCess
#define JKFullPaymentAlertView cuJKRJKFullPaymenssstAlertViewss
#define JKRepaymentCenterFootView cywfashahnssstAlertViewss
#define JKCollectMoneyViewController sgGSefashgsJKCollectMoneyViewContross
#define JKColletMoneyTopViewCell cGhseJKColletMoneyTopViewCellViewContross
#define JKCollectMoneyViewCell gsgeJKCJKCollectssgsrt
#define JKLoanConfirmViewController pshshanConfirmViewControllerollectssgsrt
#define requestLoanInfo pJgsgKLoanConfirmViewControllerewContro
#define JKEatNowViewController sdJgsgKJKEatNowVidsdewControllerCtro
#define JKCreditingViewController fsfJKCreditingViewConerCtrgsg
//JKAddCardViewController
#define requestUserName fsfrequestUserNCtrgs
#define requsetBankName GS6requsetBankNamerNgsg
#define JKAddCardViewCell GS6JKAddCardViessderNyww
//JKBankCardListViewController
#define JKBankCardListViewController gseJKBankCardListViewControllywtgs
#define pushAddCardVc gdpushAddCardVcistVyetl
#define requestUpdateDefault grequestUpdateDefaultste
#define JKBankcardListViewCell gshJKBankcardListViewCellwty
//JKLoanRecordViewController
#define  JKLoanRecordViewController yetKBagsgshhwewCeldh
#define  requestLoanRecord reqgshjuestLoanhshRecordgs
#define  JKLoadRecordViewCell eqgshjuJKLoadRecordVsordgss
#define  JKLoadRecordHeaderView wdKLoadJKLoadRecordHeddq
#define  JKAssistanceViewController bbbchsgJKAssistanceViewControllteq
#define  initWebView bcffwinitWebViewollteq
#define  requestCustomerserviceUrlWith yetestCustomerserviceUrlWithyu
#define  showTelAlert yetesshowTexlAxlerthshst
#define  setupNavBarButton jdNgdgdavBarButtonxlerhdgt
#define  backtoTop RWbacktoToplerhdgGSt
#define  JKAssistancPhoneViewCell RWbacktoTFSJKAssistaSt
#define  JKAssistancProblemsViewCell HSDHJKAssistancProblemsVstaSt
#define  PHCustomerServiceTelView PHCustomGDGerServicVDGBeTelV
#define  setupLabel PHCustsetupLabelDGBeTelV
#define  tabKefu PtabKefubelDG
//JKAboutViewController
#define  JKAboutViewController PtaGSHGSJJKAbouHGDHGontrollerbelDG
#define  JKAboutViewCell JKAHSboutDHGSViewCellGHSGDG
#define  JKAboutHeaderView SHJKAbouGSHJSHerViewSY
#define  cellWithHight celSGSBlWithHGSWe
//JKSetupViewController
#define  JKSetupViewController cJKSetupViewConddtrollerthigse
#define  PHBaseViewController cJKtevBaseViewCgsontrolgd
#define  PHDeleteAccountViewController cJPHDeffsleteAccountViewConontrolgd
#define  JKLanguageAlertView ddJKLanguddagyetrolgd
#define  JKResetPhoneAlert gsfetPhoneAlertgstey
#define  JKSetupInfoViewCell cJJKSetupIshhsketTEHd
#define  setupUI cJJKSesetupUItTEHdGHS
#define  pushResetPhoneNumber GDGusGSGhResetPhYEGHdGHS
#define  showLanguageAlert cyypushowDGDLangTEG
#define  refreshRootViewController teushowDGrYEtViewControllerD
#define  clickToUpdateApp ghhscpusclickToUpdateApGDG
#define  clickLogoutBtn getdAtegsgyevsG
#define  pushDeleteAccountVc hdgpushDeleteAchdhvsG
#define  TRCustomAlert gdfRCustomAlertAchdyet
#define  phoneView fsdRCuphoneViewdyetfgdg
#define  requestDeleteAccount derequeyegeAccoundg
#define  deleteAccountSucc rtdeleteAccsountSusgs
#define  deleteAccountFaile USGdeleteAccoBSuntFaiSGle
//JKSecurityVerificatViewController
#define  JKSecurityVerificatViewController gdgJKSecurityVerontrolleroBGle
#define  JKResetPhoneViewController retDShoneViewControlETEG
#define  JKLoginModelParam rJKLoginModelParamlETEG
#define  JKResetPhoneSuccessViewController DJKReDsetDPhoDneSDucceDssVieDwController
#define  textFieldTextChange DldTextChangDrDWdd
#define  JKVerificationCodeViewController UHsgJKVerificatioller5SG7gs
#define  timeBtnUpDateOnClicks TEeBtnUpDateOYEBVickslTEJ
#define  loginBtnClick HDDgdgTEeBtnTEeBtnGSG
#define  updateTime DsEsupdateTteggs
#define  getVerificationCode fdgerificationCodeteggssf
#define  upDataMobilePhone gfpDataMobilePhongsge
#define  PHRepayBankcardListViewCell FDsgPHRerdLddistVisewshCehdll
#define  setRepayCellWithModel fddhsetRepModgsfhdll
#define  PHRepayWebViewController fsgeDGDHHHHPHRepREYSHontrGS
#define  PHOfflineRepayModel GSFPHOffliBDneRepayModelrGS
#define  PHRepayStyleModel GFSHDayModGDFJFJ
#define  PHCashRepayMoneyAlert FSDPHCashReGSFDpayMGDoModGDFJFJ
#define  PHEWalletRepayMoneyAlert DSG3HEWalletRepayMoneyA6dss
#define  setupViewModel gfadhGSGayMoGDs
#define  PHRePayBankCardListViewController dsvDGAFPHRePayBastViewCerSGayMoGDs
#define  PHRepaymentOneViewController PsgshSSsvDPHRekjdymentOollerReayB
#define  JKRepaymentViewController PsgsSsvJKRepayddmentViewddConddtrsh
//JKWithdrawalMoneyViewController
#define  JKWithdrawalMoneyViewController Psgsgsjhsh7SVHwddConddtrsh
#define  setupTopView FDsPsgsgsjGSGddConddtrshFS
#define  PHWithdrawalMoneyOneViewController FDssgstwywusbbSGS
//PHAddEWalletViewController
#define  PHAddEWalletViewController GDFDsrevdwywusbbFFSGHJ
#define  PHAddEWalletAnctionCell GHAAHJyGSHSJHJAJAUYW62J
#define  JKinputBlock GSHHSJAUYWYEGHEB
#define  JKEndInputBlock GFS7WGSJYEG6DHDH
#define  inputBlock SsGFGS7356Dtr
#define  endinputBlock gfs7yethshgfs
#define  PHEWelletListViewController gfs7hsHDJSHSDSPHewConHDHtrolJHDhgfs

#endif /* CodeObfuscation_h */


