# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PresiMex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'SSZipArchive','~>2.4.3' #zip压缩
  pod 'Masonry' #OC布局类
  pod 'JKCategories','~> 1.9.3' #系统类扩展
  pod 'MBProgressHUD','~> 1.2.0'
  pod 'SDWebImage', '~> 5.9.5'
  pod 'AFNetworking','~>4.0.0'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'ZZCircleProgress'
  pod 'IQKeyboardManager'
#  pod 'RollingNotice' #轮播广告
#  pod 'MarqueeLabel'
#  pod 'JhtMarquee'
  

#  pod 'DZNEmptyDataSet'  
  pod 'AppsFlyerFramework'

  pod 'FirebaseCore'

  pod 'Firebase/Messaging'
#  pod 'Bugly'

#  pod 'IQKeyboardManager', '~>6.5.11'
 
  

  # Pods for PresiMex

  target 'PresiMexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PresiMexUITests' do
    # Pods for testing
  end

  
  
# post_install do |installer|
#     installer.generated_projects.each do |project|
#           project.targets.each do |target|
#               target.build_configurations.each do |config|
#                   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#                end
#           end
#    end
# end
#  
  
  
end




#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      # 将 iOS Deployment target 设置为 11.0
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#    end
#  end
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      xcconfig_path = config.base_configuration_reference.real_path
#      xcconfig = File.read(xcconfig_path)
#      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
#      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
#    end
#  end
#end







post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 将 iOS Deployment target 设置为 11.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
